#!/bin/bash

## Levantar el servicio de cache ya que en
## Archlinux init.d ya no forma parte del sistema
# Se ejecuta con permisos de usuario no elevados
# al ejecutarse varias veces es capaz de reconocer
# instancias previas y únicamente permanece la primera.
/usr/lib/SCMiddleware/idocachesrv
sleep 0.3

## Abrir la herramienta SCManager
/usr/lib/SCMiddleware/SCManager

exit $?
