#!/bin/bash

function delete_scm_daemons (){
    ### Eliminar el daemon midware porque es una obscenidad en consumo de recursos
    while ps aux | grep -v grep | grep -c "[^A-Za-z]idocachesrv"
    do
        PROC_NUM=$( ps aux | grep -v grep | grep idocachesrv | sed 's| * |\t|g' |
                        cut -f 2 | sort | head -n 1 )
        echo    kill -s 15 $PROC_NUM
        kill -s 15 $PROC_NUM
    done
}

delete_scm_daemons
sleep 0.3

## Levantar el servidor de cache
/usr/lib/SCMiddleware/idocachesrv
sleep 0.3

## Abrir la herramienta
/usr/lib/SCMiddleware/SCManager

delete_scm_daemons

exit 0
